### ISSUE TITLE
Updating to Rust 1.3

### ISSUE THREAD

**Issue by crossroads1112** [mcandre/rustcheck#10]
Alright, so I'm happy to help you out here (there are a lot of issues, mostly with typing. That's changed a lot in Rust), but I need to understand desired behavior. 

One of the great attributes of Rust is trait-based generics. Is there a reason you need `gen_int`, `gen_bool` etc. instead of just using `rand::thread_rng().gen()` and just implementing the `rand::Rand` trait for all non-primitive types (`Vec`, `String` etc.)? If naming is important, you could wrap `thread_rng().gen()`, I suppose.

**Comment by mcandre** [comment]
An able-to-be-randomly generated trait would be a great idea! Then `for_all` could just take a property to test, and a sequence of implementations.

**Comment by crossroads1112** [comment]
Is this kinda what you're looking for? https://github.com/crossroads1112/rustcheck

**Comment by mcandre** [comment]
Yeah! Feel free to submit a pull request when you've got a trait-based implementation working!

**Comment by crossroads1112** [comment]
I will, might I suggest that you transition over to using `cargo`? It makes dependencies and testing much easier

**Comment by mcandre** [comment]
That is also a very good idea

**Comment by crossroads1112** [comment]
Hey, sorry, it has taken me so long (college apps were due so this took a back-burner).

The thing is, so much is different in the new version that merging is probably a lost cause. What if I just gave you write access to my rustcheck repository and you took this one down?

**Comment by mcandre** [comment]
Linking to https://github.com/mcandre/rustcheck/pull/11

Awesome, thanks for the pull request!
